apiVersion: v1
kind: Service
metadata:
  name: card-manager-app
  namespace: card-manager
spec:
  selector:
    app: card-manager-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
