apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: card-manager
type: Opaque
stringData:
  POSTGRES_DB: card_manager
  POSTGRES_USER: card_manager
  POSTGRES_PASSWORD: card_manager
  DATABASE_URL: postgres://card_manager:card_manager@postgres:5432/card_manager
